### ISSUE TITLE
What is the License for this codebase?

### ISSUE THREAD

**Issue by derek-virtustream** [scottt/python-vmci#1]
Hi @scottt; I was wondering what License you were releasing this under? I'd like to use it in a cloud-proxy tool.

**Comment by scottt** [comment]
@derek-virtustream, these are all licensed under the same (very permissive) terms as Python itself. Sorry for the late reply. I've since added a LICENSE file.

**Comment by derek-virtustream** [comment]
No problem with the late reply; I am sure you're busy. Thanks for updating the repo with the License. Very pleased to see a PSF2 on it!
